using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SettingData : StorageBase<SettingData>
{
    public bool IsMusicOn
    {
        get
        {
            return mIsMusicOn;
        }
        set
        {
            mIsMusicOn = value;
            Save();
        }
    }
    [SerializeField] private bool mIsMusicOn = true;

    public bool IsSoundOn
    {
        get
        {
            return mIsSoundOn;
        }
        set
        {
            mIsSoundOn = value;
            Save();
        }
    }
    [SerializeField] private bool mIsSoundOn = true;
}