using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using DG.Tweening;

public class PanelGameAni : MonoBehaviour
{
    [SerializeField] RectTransform mRctTop;
    [SerializeField] RectTransform mRctCenter;

    [SerializeField] RectTransform mRctEndingsBtn;

    [SerializeField] RectTransform mRctSlotBG;
    [SerializeField] RectTransform mRctSlotBtns;

    [SerializeField] RectTransform mRctSoundBtns;

    public void Init()
    {
        mRctTop.anchoredPosition = new Vector2(0, 180);
        mRctCenter.anchoredPosition = new Vector2(0, -560);

        mRctEndingsBtn.anchoredPosition = new Vector2(100, -235);

        mRctSlotBG.anchoredPosition = new Vector2(0, -125);
        mRctSlotBG.sizeDelta = new Vector2(mRctSlotBG.sizeDelta.x, 249);

        mRctSlotBtns.anchoredPosition = new Vector2(0, -305);
        mRctSoundBtns.anchoredPosition = new Vector2(0, -470);

        mRctTop.DOAnchorPosY(0, 0.5f);
        mRctCenter.DOAnchorPosY(0, 0.5f);

        mRctEndingsBtn.DOAnchorPosX(-10, 0.3f).SetDelay(0.5f);
    }

    public void ReadyPlay(float pDuration)
    {
        mRctSlotBG.DOAnchorPosY(-180, pDuration);
        mRctSlotBG.DOSizeDelta(new Vector2(mRctSlotBG.sizeDelta.x, 395), pDuration);

        mRctSlotBtns.DOAnchorPosY(-390, pDuration);
        mRctSoundBtns.DOAnchorPosY(-680, pDuration);
    }
}